(function (root) {
  'use strict';
  const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const button = (label, action, cls = '') => `<button class="${cls}" data-action="${action}">${label}</button>`;
  function home({ pack, packValid, subjectNames, subjectIcons, recentQuiz, recentArithmetic, arithmeticNames, notices }) {
    return `<section class="v1-hero"><div><span class="eyebrow">三年级上册 · 单元挑战</span><h1 tabindex="-1">今天想挑战哪一科？</h1><p>语文、数学、英语每轮10题，也可以继续口算训练。<br>答完自动进入下一题，错题会在最后集中复习。</p><div class="chips"><span>✓ 教材范围可选</span><span>✦ 每轮10题</span><span>⌁ 本地保存</span></div></div><div class="v1-mark" aria-hidden="true"><b>3</b><span>科知识小冒险</span></div></section>
    <section class="subject-grid" aria-label="选择学科">${['chinese','math','english'].map(subject => `<button class="subject-card ${subject}" data-subject="${subject}" ${packValid ? '' : 'disabled'}><span class="subject-icon">${subjectIcons[subject]}</span><b>${subjectNames[subject]}</b><small>${subject === 'chinese' ? '词语 · 课文 · 古诗' : subject === 'math' ? '概念 · 计算 · 应用' : 'Words · Talks · Stories'}</small><em>选择范围 →</em></button>`).join('')}<button class="subject-card arithmetic" data-action="arithmeticSetup"><span class="subject-icon">🔢</span><b>口算营地</b><small>V0经典模式 · 三类口算</small><em>选择难度 →</em></button></section>
    <section class="v1-status card"><div><b>当前内容</b><span>${escape(pack.title)} · 内容包 ${escape(pack.contentVersion)}</span></div><div><b>最近成绩</b><span>${recentQuiz ? `${subjectNames[recentQuiz.subject]} ${recentQuiz.score}/10` : recentArithmetic ? `${arithmeticNames[recentArithmetic.type]} ${recentArithmetic.score}/10` : '完成一轮后会显示在这里'}</span></div></section>${notices.length ? `<p class="system-notice">${notices.map(escape).join('<br>')}</p>` : ''}`;
  }
  function scopeSetup({ subject, subjectNames, subjectIcons, grades, semesters, units, scope, questionCount }) {
    return `<section class="setup-title">
      ${button('← 返回学科选择','home','text-button')}
      <span class="eyebrow">${subjectIcons[subject]} ${subjectNames[subject]}</span>
      <h1 tabindex="-1">选择学习范围</h1><p>选择已经学过的单元，准备开始吧。</p>
    </section><section class="scope-card card">
      <label>年级<select id="scope-grade">${grades.map(grade => `<option value="${grade}" ${scope.grade === grade ? 'selected' : ''}>${grade}年级</option>`).join('')}</select></label>
      <label>学期<select id="scope-semester">${semesters.map(semester => `<option value="${semester}" ${scope.semester === semester ? 'selected' : ''}>${semester === 1 ? '上学期' : '下学期'}</option>`).join('')}</select></label>
      <label>单元<select id="scope-unit" ${units.length ? '' : 'disabled'}>${units.map(unit => `<option value="${escape(unit.id)}" ${scope.unitIds.includes(unit.id) ? 'selected' : ''}>${escape(unit.label)} · ${escape(unit.title)}</option>`).join('')}</select></label>
      <div class="scope-summary"><b>本范围有${questionCount}道题</b><span>${questionCount >= 10 ? '每轮随机选10题。' : '还不足10题，请选择其他学习范围。'}</span></div>
      <button class="primary wide" data-action="startQuiz" ${questionCount >= 10 ? '' : 'disabled'}>开始10题 →</button>
    </section>`;
  }
  function arithmeticSetup({ config, names, levelNames, recent, notice }) {
    return `<section class="setup-title">${button('← 返回学科选择','home','text-button')}<span class="eyebrow">口算营地</span><h1 tabindex="-1">选一个训练区域</h1></section><section class="setup card"><div class="section-heading"><h2>今天去哪里？</h2><span>选好难度就能出发</span></div><div class="destinations">${Object.entries(names).map(([id, name], i) => `<button data-type="${id}" class="destination ${config.type === id ? 'selected' : ''}" aria-pressed="${config.type === id}"><span class="icon">${['🌳','💧','⛰'][i]}</span><b>${name}</b><small>${['两位数 · 三位数加法','一位数 × ÷ 一位数','两位数 × ÷ 一位数'][i]}</small></button>`).join('')}</div><div class="options"><label>难度<select id="level">${Object.entries(levelNames).map(([value,label]) => `<option value="${value}" ${config.level === value ? 'selected' : ''}>${label}</option>`).join('')}</select></label><label>玩法<select id="mode"><option value="practice" ${config.mode === 'practice' ? 'selected' : ''}>轻松练习 · 不计时</option><option value="challenge" ${config.mode === 'challenge' ? 'selected' : ''}>挑战自己 · 记录用时</option></select></label>${button('开始口算 →','start','primary')}</div><p class="note">${config.type === 'addition' ? '热身：两位数不进位；进阶：两位数加法；挑战：包含三位数。' : '热身使用1—5的小因子；进阶和挑战使用1—9。除法都能整除。'}</p></section><div class="history">${recent ? `上次口算：${names[recent.type]} · ${recent.score}/10题正确。` : '你的第一枚口算足迹，等着你来点亮。'}${notice ? `<br>${notice}` : ''}</div>`;
  }
  function arithmeticQuestion({ question, questions, answers, config, names, levelNames }) {
    return `<section class="game-head">${button('← 返回口算','leave','text-button')}<span>${names[config.type]} · ${levelNames[config.level]}</span><span id="timer">${config.mode === 'challenge' ? '0秒' : '慢慢想，不着急'}</span></section>${progress(questions,answers,answers.length)}<section class="play-grid"><div class="question card"><span class="eyebrow">第 ${answers.length + 1} / 10 题</span><h1 tabindex="-1">${question.a} ${question.op} ${question.b} <span>= ?</span></h1><div id="answer" class="answer" role="status" aria-label="当前答案">输入你的答案</div><div id="feedback" aria-live="polite"><p class="muted">想好了，就按「提交答案」</p></div></div><div class="keypad card"><p>点一点，填答案</p><div class="keys">${[1,2,3,4,5,6,7,8,9].map(number => button(number,String(number))).join('')}${button('清空','clear','small')}${button(0,'0')}${button('⌫','delete')}</div><div id="submit-area">${button('提交答案 ↵','submit','primary wide')}</div><small>键盘数字输入 · Enter 提交 · 退格删除</small></div></section>`;
  }
  function quizQuestion({ session, unit, subject, subjectNames, subjectIcons, feedback }) {
    const question=session.questions[session.index];
    return `<section class="game-head">${button('← 返回范围','scopeSetup','text-button')}<span>${subjectIcons[subject]} ${subjectNames[subject]}</span><span>${unit ? escape(unit.label) : '已选范围'}</span></section>${progress(session.questions,session.answers,session.index)}<section class="quiz-card card"><span class="eyebrow">第 ${session.index + 1} / ${session.questions.length} 题 · ${escape(question.learningGoal)}</span><h1 tabindex="-1">${escape(question.prompt)}</h1><div class="choice-list" role="group" aria-label="答案选项">${question.options.map((option,index) => `<button data-option="${index}" class="choice ${session.selection === index ? 'selected' : ''} ${feedback ? index === question.answerIndex ? 'correct-choice' : index === feedback.selected ? 'wrong-choice' : '' : ''}" aria-pressed="${session.selection === index}" ${feedback ? 'disabled' : ''}><span>${index + 1}</span>${escape(option)}</button>`).join('')}</div><div id="quiz-feedback" aria-live="polite">${feedback ? `<div class="feedback ${feedback.correct ? 'success' : 'try'}"><b>${feedback.correct ? '✦ 答对啦！' : `正确答案：${escape(question.options[question.answerIndex])}`}</b><p>${escape(question.explanation)}</p></div>` : '<p class="muted">选好答案后提交，也可以按键盘1—4。</p>'}</div><div id="quiz-submit">${feedback ? `<button class="primary wide" disabled>${session.index === session.questions.length - 1 ? '正在整理成绩…' : '即将进入下一题…'}</button>` : button('提交答案 ↵','quizSubmit','primary wide')}</div></section>`;
  }
  function progress(questions, answers, current) {
    return `<div class="progress" aria-label="第${current + 1}题，共${questions.length}题">${questions.map((_,index) => `<span class="${index < answers.length ? (answers[index].correct ? 'done' : 'review') : index === current ? 'current' : ''}">${index + 1}</span>`).join('')}</div>`;
  }
  function resultCard({ score, prefix, saved, restartAction, label }) {
    return `<section class="result card"><span class="eyebrow">本轮完成 · ${label}</span><div class="badge" aria-hidden="true">✦</div><h1 tabindex="-1">${score === 10 ? '这次，全部拿下！' : '又完成了一次小冒险！'}</h1><div class="score">${score}<span> / 10题正确</span></div><p>${prefix}${score === 10 ? '带着这份信心，继续探索吧。' : '错题已经整理在下面，下次再试试。'}</p><p class="note">${saved ? '成绩已保存在当前浏览器。' : '本次成绩未能保存，但不影响继续玩。'}</p><div class="result-actions">${button('再来一轮 →',restartAction,'primary')}${button('返回首页','home','secondary')}</div></section>`;
  }
  function arithmeticReview(wrong, hint) { return wrong.length ? `<section class="review-list"><h2>带走这些小方法</h2>${wrong.map(answer => `<article class="card"><b>${answer.q.a} ${answer.q.op} ${answer.q.b} = ${answer.q.answer}</b><span>你的答案：${answer.value}</span><p>${hint(answer.q)}</p></article>`).join('')}</section>` : ''; }
  function quizReview(wrong) { return wrong.length ? `<section class="review-list"><h2>错题小复盘</h2>${wrong.map(answer => `<article class="card"><b>${escape(answer.question.prompt)}</b><span>你的答案：${escape(answer.question.options[answer.selected])}</span><p><strong>正确答案：</strong>${escape(answer.question.options[answer.question.answerIndex])}</p><p>${escape(answer.question.explanation)}</p></article>`).join('')}</section>` : ''; }
  function error(message) { return `<section class="card error-state"><h1 tabindex="-1">暂时不能开始</h1><p>${escape(message)}</p>${button('返回首页','home','primary')}</section>`; }
  const api={home,scopeSetup,arithmeticSetup,arithmeticQuestion,quizQuestion,resultCard,arithmeticReview,quizReview,error};
  if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.AppViews=api;
})(typeof globalThis!=='undefined'?globalThis:this);
